codecov:
  branch: develop
  max_report_age: off
  fixes:
    - "io/github/config4k::src/main/io.github.config4k"
    
coverage:
  status:
    project:
      default:
        # Fail the status if coverage drops by >= 0.1%
        threshold: 0.1