-
  title: 快速上手
  path: docs
- 
  title: 组件
  path: components
  groups:
      -
        title: Button
        subTitle: 按钮
        path: button
        componentName: Button
      -
        title: Dropdown
        subTitle: 下拉菜单
        path: dropdown
        componentName: dropdown
   